language: node_js
script: yarn docs:build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  local-dir: /docs/.vuepress/dist/
  on:
    branch: gh-pages
