version: '2'
services:
  webapp:
    # container_name: contest-webapp
    build: ..
    image: contest-unf
    restart: always
    environment:
      FLASK_CONFIG: '/webapp/config/production.py'
  db:
    image: "mongo"
    restart: "always"
#     volumes:
#       - deploy_contest-db-2017fa:/data/db
# volumes:
#   deploy_contest-db-2017fa:
